import visualize


NO_OF_PACKETS_SENDER1=10
NO_OF_PACKETS_SENDER2=20
NO_OF_PACKETS_SENDER3=15

FPS_OF_SENDER1=9
FPS_OF_SENDER2=80
FPS_OF_SENDER3=34
FPS_OF_NODE1=0
FPS_OF_NODE2=150

BUFFER_OF_NODE1=3
BUFFER_OF_NODE2=4


visual=visualize.Visualize(NO_OF_PACKETS_SENDER1,NO_OF_PACKETS_SENDER2,NO_OF_PACKETS_SENDER3,FPS_OF_SENDER1,FPS_OF_SENDER2,FPS_OF_SENDER3,FPS_OF_NODE1,FPS_OF_NODE2,BUFFER_OF_NODE1,BUFFER_OF_NODE2)
visual.start()



